kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper-dep
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper-server
        image: "docker.io/bitnami/zookeeper:3-debian-10"
        ports:
        - containerPort: 2181
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
