apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka-zookeeper
  namespace: kafka
  labels:
    type: local
    component: zookeeper
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"