apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka
  namespace: kafka
  labels:
    type: local
    component: kafka
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"